### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by raythurnvoid** [jakobrosenberg/svelte-prism#24]
I've been working on a typescript porting with an additional fix to allow the source to be an empty string.

Check my repo and tell me whether you'd like a PR: https://github.com/raythurnevoid/svelte-prism/tree/typescript

**Comment by jakobrosenberg** [comment]
Hi @raythurnevoid . Sorry about the slow reply. Your project looks great.

If you submit a PR I'll have a look at it. The more documentation, the better. 🙂
