### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by kuchaguangjie** [jakobrosenberg/svelte-prism#40]
sveltekit is released, can you make a new release ?

**Comment by jakobrosenberg** [comment]
I'm not sure I follow. Can you elaborate?

**Comment by kuchaguangjie** [comment]
The last release is `v1.1.3 (2020-06)`, there are new commits since then, could you make a new release to include those changes?

**Comment by jakobrosenberg** [comment]
It seems Github hasn't picked up on the latest releases since I changed to  `standard-version`, but you can see the releases here. https://www.npmjs.com/package/svelte-prism

**Comment by kuchaguangjie** [comment]
Ok, got it.
