### ISSUE TITLE
Different languages

### ISSUE THREAD

**Issue by bernaferrari** [jakobrosenberg/svelte-prism#8]
How can I support different languages, like Dart? It seems it only supports HTML (which is nice!), but I wish more. Maybe you could expose a custom language URL and let the user add it?

**Comment by jakobrosenberg** [comment]
``require('prismjs/components/prism-daft')`` should work.

**Comment by bernaferrari** [comment]
ohhhhh that's so simple and intuitive! Thanks a lot!!!!
